language: shell

before_install:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats
  - sudo apt-get install -qq expect

services:
  - docker

script:
  - shellcheck ./terminusdb-container
  - bats .ci/test/basic.bats
  - ./terminusdb-container test
