language: node_js

before_install:
  - sudo apt-get install expect
  - npm install -g bats

services:
  - docker

script:
  - shellcheck ./terminusdb-container
  - bats .ci/test/basic.bats
  - ./terminusdb-container test
